export const CHART_CANDLESTICK = "Candle Stick"
export const CHART_HEIKIN_ASHI = "Heikin Ashi"
export const CHART_KAGI = "Kagi"
export const CHART_LINE = "Line"
export const CHART_POINT_FIGURE = "Point & Figure"
export const CHART_RENKO = "Renko"